/*
389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
 var findTheDifference = function(s, t) {
    let objS = {}
    for(let i=0; i<s.length; i++) {
        objS[s[i]] = objS[s[i]] ? ++objS[s[i]] : 1
    }
    for(let i=0; i<t.length; i++) {
        if(objS[t[i]] === undefined) return t[i]
        else if(objS[t[i]] === 1) delete objS[t[i]] 
        else objS[t[i]]--
    }
};